# Generated by Django 5.2.1 on 2025-05-29 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(upload_to='', verbose_name='Фото'),
        ),
    ]
