# Generated by Django 5.2.1 on 2025-06-03 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0007_alter_management_leader_alter_management_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='management',
            name='leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leader', to='app2.person'),
        ),
        migrations.AlterField(
            model_name='management',
            name='managers',
            field=models.ManyToManyField(related_name='managers', to='app2.person', verbose_name='Менеджеры'),
        ),
    ]
