# Generated by Django 5.2.1 on 2025-06-04 14:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0008_alter_management_leader_alter_management_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='resume',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='program',
            name='benefits',
            field=ckeditor.fields.RichTextField(verbose_name='Преимущества'),
        ),
        migrations.AlterField(
            model_name='program',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Описание'),
        ),
    ]
